// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AdminFormModal: typeof import('./dashboard/pages/dashboard/admins/components/AdminFormModal.vue')['default']
    Counter: typeof import('./common/components/Counter.vue')['default']
    DarkSwitch: typeof import('./common/components/DarkSwitch.vue')['default']
    DeviceFormModal: typeof import('./dashboard/components/device/DeviceFormModal.vue')['default']
    Footer: typeof import('./common/components/Footer.vue')['default']
    JobFormModal: typeof import('./dashboard/pages/dashboard/jobs/components/JobFormModal.vue')['default']
    LayoutHeader: typeof import('./common/components/Layout/LayoutHeader.vue')['default']
    LayoutSider: typeof import('./common/components/Layout/LayoutSider.vue')['default']
    Map: typeof import('./common/components/Map.vue')['default']
    README: typeof import('./common/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillFormModal: typeof import('./dashboard/pages/dashboard/skills/components/SkillFormModal.vue')['default']
    UserFormModal: typeof import('./dashboard/pages/dashboard/users/components/UserFormModal.vue')['default']
  }
}

export {}
