// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABadgeRibbon: typeof import('ant-design-vue/es')['BadgeRibbon']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AdminFormModal: typeof import('./dashboard/pages/dashboard/admins/components/AdminFormModal.vue')['default']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    Counter: typeof import('./common/components/Counter.vue')['default']
    DarkSwitch: typeof import('./common/components/DarkSwitch.vue')['default']
    DeviceFormModal: typeof import('./dashboard/components/device/DeviceFormModal.vue')['default']
    EditorFormModal: typeof import('./dashboard/pages/dashboard/admins/components/EditorFormModal.vue')['default']
    Footer: typeof import('./common/components/Footer.vue')['default']
    JobFormModal: typeof import('./dashboard/pages/dashboard/jobs/components/JobFormModal.vue')['default']
    LanguagesLevel: typeof import('./dashboard/pages/dashboard/users/freelance/components/LanguagesLevel.vue')['default']
    LayoutHeader: typeof import('./common/components/Layout/LayoutHeader.vue')['default']
    LayoutSider: typeof import('./common/components/Layout/LayoutSider.vue')['default']
    Map: typeof import('./common/components/Map.vue')['default']
    PostFormModal: typeof import('./dashboard/pages/dashboard/posts/components/PostFormModal.vue')['default']
    README: typeof import('./common/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillFormModal: typeof import('./dashboard/pages/dashboard/skills/components/SkillFormModal.vue')['default']
    SocialMedia: typeof import('./dashboard/pages/dashboard/users/agence/components/SocialMedia.vue')['default']
    UserFormModal: typeof import('./dashboard/pages/dashboard/users/components/UserFormModal.vue')['default']
  }
}

export {}
