// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABadgeRibbon: typeof import('ant-design-vue/es')['BadgeRibbon']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Counter: typeof import('./common/components/Counter.vue')['default']
    DarkSwitch: typeof import('./common/components/DarkSwitch.vue')['default']
    DeviceFormModal: typeof import('./dashboard/components/device/DeviceFormModal.vue')['default']
    Footer: typeof import('./common/components/Footer.vue')['default']
    LayoutHeader: typeof import('./common/components/Layout/LayoutHeader.vue')['default']
    LayoutSider: typeof import('./common/components/Layout/LayoutSider.vue')['default']
    Map: typeof import('./common/components/Map.vue')['default']
    README: typeof import('./common/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserFormModal: typeof import('./dashboard/pages/dashboard/users/components/UserFormModal.vue')['default']
  }
}

export {}
